queryEnvKey: Do not use ':' in name
Without this, and with otopi-generated answer files, an answer file can
have e.g.:

QUESTION/1/queryEnvKey_input:somekey=str:somevalue
QUESTION/1/queryEnvKey_input:otherkey=str:othervalue

Then, feeding this to engine-setup as --config-append, fails with:

Failed to read config file ans1
Traceback (most recent call last):
  File "/usr/share/otopi/plugins/otopi/core/config.py", line 139, in _init
    readfunc(fp)
  File "/usr/lib64/python3.6/configparser.py", line 718, in read_file
    self._read(f, source)
  File "/usr/lib64/python3.6/configparser.py", line 1092, in _read
    fpname, lineno)
configparser.DuplicateOptionError: While reading from
'ans1' [line 28]: option 'QUESTION/1/queryEnvKey_input' in section
'environment:default' already exists

That's because configparser allows "=|:" as delimiters. So use "_".

Change-Id: I1bcba8c7b73fab827905340b4606e535a2a1e03d
Signed-off-by: Yedidyah Bar David <didi@redhat.com>